site_name: Devkit q&kdb+
nav:
  - Overview: index.md
  - Installing: install.md
  - Data type: data_type.md
  - Type casting: type_casting.md
  - List synctax: list_synctax.md
  - List: list.md
  - Dictionaries: Dictionaries.md
  - Table: table.md
  - Verb: verb.md
  - Function: function.md
  - Queries: queries.md
  - Inter Process Communicatio: inter_process-communicatio.md
  - Message Handler: message_handler.md
  - Table on disk: table_on_disk.md
theme: readthedocs
extra_javascript:
  - js/extra.js
extra_css:
  - css/extra.css